# Generated by Django 4.2.28 on 2026-02-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PopularDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_city", models.CharField(max_length=100)),
                (
                    "origin_code",
                    models.CharField(help_text="IATA code, e.g. IST", max_length=4),
                ),
                ("destination_city", models.CharField(max_length=100)),
                (
                    "destination_code",
                    models.CharField(help_text="IATA code, e.g. CDG", max_length=4),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("image", models.ImageField(upload_to="destinations/")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Popular Destination",
                "verbose_name_plural": "Popular Destinations",
                "ordering": ["order", "destination_city"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_number", models.CharField(default="", max_length=20)),
                ("office_address", models.TextField(blank=True)),
                ("office_hours", models.CharField(blank=True, max_length=100)),
                ("office_phone", models.CharField(blank=True, max_length=20)),
                ("office_email", models.EmailField(blank=True, max_length=254)),
                ("office_map_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
