# Generated by Django 4.2.28 on 2026-02-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populardestination",
            name="destination_code",
            field=models.CharField(help_text="IATA code, e.g. CDG", max_length=3),
        ),
        migrations.AlterField(
            model_name="populardestination",
            name="image",
            field=models.ImageField(blank=True, upload_to="destinations/"),
        ),
        migrations.AlterField(
            model_name="populardestination",
            name="origin_code",
            field=models.CharField(help_text="IATA code, e.g. IST", max_length=3),
        ),
        migrations.AlterField(
            model_name="populardestination",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
