# Generated by Django 4.2.28 on 2026-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesettings_office_map_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="office_map_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps URL — aşağıdakı formatlardan biri ilə girilə bilər:<br>• <b>maps.google.com/maps?q=ÜNVAN</b> — ünvan axtarışı<br>• <b>google.com/maps/place/AD/@lat,lng</b> — yer linki (Copy Link)<br>• <b>google.com/maps/embed?pb=…</b> — embed URL (Share → Embed)<br>Qısa linklər (goo.gl) dəstəklənmir — tam URL istifadə edin.",
                max_length=2000,
            ),
        ),
    ]
