# Generated by Django 4.2.28 on 2026-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesettings_office_map_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="populardestination",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
